### ISSUE TITLE
Unit tests fail with dyld`dyld_fatal_error

### ISSUE THREAD

**Issue by masukomi** [austinzheng/swift-lambdatron#42]
Seems that no matter what test I try and run I always end up with this:

```
dyld`dyld_fatal_error:
0x7fff5fc0109c:  int3   
0x7fff5fc0109d:  nop    
```

running XCode 6.1.1 under OS X 10.9.5

last commit is 
```
commit cb244f57f02db6ad19fc61d35dad5b0ae3779cba
Author: Austin Zheng <austinzheng@gmail.com>
Date:   Sun Mar 8 15:57:07 2015 -0700

    Adding unit tests

    Changes:
    - Added unit tests for the '.dissoc' function
    - Fixed .dissoc's arity error message
```

**Comment by austinzheng** [comment]
Thanks for bringing this to my attention. I'm going to try to get my hands on a 10.9 machine to repro this as soon as I can.

**Comment by austinzheng** [comment]
In the meantime, could you try deleting Derived Data and cleaning the build folder (`Product` + Option key --> `Clean Build Folder...`)? Let me know if you have any questions.

**Comment by masukomi** [comment]
Alas, I received the same result after deleting the contents of Derived Data and cleaning the build folder. :/

**Comment by austinzheng** [comment]
I'm still trying to get access to a 10.9 machine, hope to have one to play with this afternoon. In the meantime, just a few more questions:

- Do you have any other versions of Xcode besides 6.1.1 installed on your machine?
- Is this happening with a fresh repository you `git clone`d from GitHub?

Thanks so much, and sorry for the inconvenience.

**Comment by masukomi** [comment]
I did have another version installed when I first ran this, but I quit xcode, deleted all those files, deleted the older version just in case, emptied the trash, and then ran it again. I have made no changes to the repo since cloning, and git confirms that there have been no changes or new files added.

**Comment by austinzheng** [comment]
Thanks for clarifying that. I'm provisioning a Mavericks VM so I can try and replicate your setup.

**Comment by austinzheng** [comment]
I have "good" news; I was able to reproduce your problem on my VM running 10.9 and 6.1.1. I'll try to resolve this by tomorrow.

**Comment by austinzheng** [comment]
It seems the problem was the deployment target (e.g. https://github.com/victor/whereami/issues/13). I lowered it to 10.9, and it works fine on the VMs. Please update your branch and try again, and let me know if it's still broken. Thanks!

**Comment by masukomi** [comment]
Success!

     Executed 675 tests, with 0 failures (0 unexpected) in 20.795 (21.644) seconds

(ignore the slow time. It's a 6 year old low end Macbook)
